spring:
  datasource:
    platform: postgres
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: "validate"
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"

  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
    default-schema: test
    liquibase-schema: test

server:
  port: 8082